// assets/components/form/AppForm.jsx
import AppFormGroup from './field/AppFormGroup'

function AppForm(props) {
    return <form autocomplete="off" enctype="multipart/form-data" method="POST" novalidate>
        {props.fields.map(field => <AppFormGroup field={field}/>)}
    </form>
}

AppForm.props = {fields: {required: true, type: Array}}

export default AppForm

// assets/components/form/AppForm.vue
<script setup>
    import AppFormGroup from './field/AppFormGroup.vue'

    defineProps({fields: {required: true, type: Array}, id: {required: true, type: String}})
</script>

<template>
    <form :id="id" autocomplete="off" enctype="multipart/form-data" method="post" novalidate>
        <AppFormGroup v-for="field in fields" :key="field.name" :field="field" :form="id"/>
    </form>
</template>
